# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
#  pod 'AliyunLogProducer', '3.0.0.beta.1', :subspecs => ['Producer', 'Core', 'OT', 'CrashReporter']
  pod 'AliyunLogProducer/Producer', :path =>'../../'
  pod 'AliyunLogProducer/Core', :path =>'../../'
  pod 'AliyunLogProducer/OT', :path =>'../../'
  pod 'AliyunLogProducer/CrashReporter', :path =>'../../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Reachability'
            target.build_configurations.each do |config|
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
            end
        end
    end
end
