# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'AliyunLogSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
#  pod 'AliyunLogProducer', :path =>'../' , :subspecs => ['Core', 'Bricks', 'CrashReporter']
#  pod 'AliyunLogProducer', '2.5.0.alpha.2' , :subspecs => ['Core', 'Bricks', 'CrashReporter']
  # pod 'AliyunLogProducer', '2.3.2' , :subspecs => ['Core', 'Bricks', 'CrashReporter']
  pod 'AliyunLogProducer/Core', :path =>'../'
  pod 'AliyunLogProducer/Bricks', :path =>'../'
  pod 'AliyunLogProducer/CrashReporter', :path =>'../'
end
