# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

targets = ['iOS','iOSTests']
targets.each do |t|
    
    target t do
      # Comment the next line if you don't want to use dynamic frameworks
      use_frameworks!

      # Pods for Demo
#      pod 'AliyunLogProducer', '3.1.1', :subspecs => ['CrashReporter', 'NetworkDiagnosis', 'Trace']
      pod 'AliyunLogProducer/Producer', :path =>'../../'
      pod 'AliyunLogProducer/Core', :path =>'../../'
      pod 'AliyunLogProducer/OT', :path =>'../../'
      pod 'AliyunLogProducer/CrashReporter', :path =>'../../'
      pod 'AliyunLogProducer/NetworkDiagnosis', :path =>'../../'
      pod 'AliyunLogProducer/Trace', :path =>'../../'
    end

end

#target 'iOS' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for Demo
##  pod 'AliyunLogProducer', '2.3.8.3.beta.2' , :subspecs => ['Core', 'Bricks', 'CrashReporter', 'NetworkDiagnosis', 'Trace']
#  pod 'AliyunLogProducer/Core', :path =>'../../'
#  pod 'AliyunLogProducer/Bricks', :path =>'../../'
#  pod 'AliyunLogProducer/CrashReporter', :path =>'../../'
#  pod 'AliyunLogProducer/NetworkDiagnosis', :path =>'../../'
#  pod 'AliyunLogProducer/Trace', :path =>'../../'
#end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Reachability'
            target.build_configurations.each do |config|
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
            end
        end
    end
end
