# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AliyunLOGiOSSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AliyunLOGiOSSample
pod 'AliyunLOGiOS', :path=>"../"

end

target 'ObjectiveCDemo001' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectiveCDemo001
  pod 'AliyunLOGiOS', :path=>"../"

end
