# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AliyunLOGiOSSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AliyunLOGiOSSample
pod 'FMDB'

end

target 'ObjectiveCDemo001' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectiveCDemo001

end
